
package com.training.jetairways;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SeatAvailability", targetNamespace = "http://ifaces.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeatAvailability {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "seatsAvailable", targetNamespace = "")
    @RequestWrapper(localName = "getAvailableSeats", targetNamespace = "http://ifaces.training.com/", className = "com.training.jetairways.GetAvailableSeats")
    @ResponseWrapper(localName = "getAvailableSeatsResponse", targetNamespace = "http://ifaces.training.com/", className = "com.training.jetairways.GetAvailableSeatsResponse")
    @Action(input = "http://ifaces.training.com/SeatAvailability/getAvailableSeatsRequest", output = "http://ifaces.training.com/SeatAvailability/getAvailableSeatsResponse")
    public int getAvailableSeats(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
